// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using OrderServiceChallenge.Data;

namespace OrderServiceChallenge.Migrations
{
    [DbContext(typeof(OrderServiceChallengeContext))]
    partial class OrderServiceChallengeContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "2.1.14-servicing-32113")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            modelBuilder.Entity("OrderServiceChallenge.Models.Employee", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CPF");

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("Employee");
                });

            modelBuilder.Entity("OrderServiceChallenge.Models.LegalPerson", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd();

                    b.Property<string>("CEP");

                    b.Property<string>("CNPJ");

                    b.Property<string>("Discriminator")
                        .IsRequired();

                    b.Property<string>("Name");

                    b.HasKey("Id");

                    b.ToTable("LegalPerson");

                    b.HasDiscriminator<string>("Discriminator").HasValue("LegalPerson");
                });

            modelBuilder.Entity("OrderServiceChallenge.Models.Company", b =>
                {
                    b.HasBaseType("OrderServiceChallenge.Models.LegalPerson");


                    b.ToTable("Company");

                    b.HasDiscriminator().HasValue("Company");
                });
#pragma warning restore 612, 618
        }
    }
}
